### ISSUE TITLE
When adding filter, values only listed after operator (!=/=) selected.

### ISSUE THREAD

**Issue by kgruschow** [ICJIA/arrest_explorer#1]
https://icjia.illinois.gov/arrestexplorer/?plot_type=bar&value=arrestees&split=race&by_year=true&format_category=indices

**Comment by miserman** [comment]
bcdceced653c61c4dcd7ef57d1158c7fb46658c4 changes this to fill in type (operator) when aspect is changed.

**Comment by kgruschow** [comment]
The UI seems to have been entirely changed for this in a way that resolves this specific issue well.(other UI requests aside)
