### ISSUE TITLE
Lack of "Home" button / ability to return settings to default.

### ISSUE THREAD

**Issue by ErnstMelchior** [ICJIA/arrest_explorer#10]
**Describe Issue**
The data button at the lower right of the screen is a toggle switch and if users click on it without remembering what they did, it is not obvious how to escape from where they got to.
![image](https://user-images.githubusercontent.com/41635929/118010284-7f379900-b314-11eb-8181-37a86beef4b3.png)

**Location of Text or Control**
Click on the data toggle.
**Current Text or Control**

**Proposed new text/control**
The Arrest Explorer logo should be a "home" key and should function to return the screen to showing the graph and the options at the right (it need not be a toggle switch like the data toggle.)

**Comment by kgruschow** [comment]
for discussion:

1. Personally I find the click/toggle function of the data button to be fairly consistent with other user interfaces.
2. I do not find the wording of "data" informative at all for knowing what the controls contained are.
3. I agree with the need for a home button to reset settings, see also #4  .

**Comment by miserman** [comment]
bcdceced653c61c4dcd7ef57d1158c7fb46658c4 adds a "reset view" button in the data menu, and makes the logo and title clickable for the same effect.
