### ISSUE TITLE
User Interface for Year is cludgy

### ISSUE THREAD

**Issue by ErnstMelchior** [ICJIA/arrest_explorer#13]
**Is your feature request related to a specific use case? Please describe.**
This applies to the year selection slider bar at right in all cases.  In Google Chrome I found it clumsy and annoying -- had trouble getting the exact year I wanted.

**Describe the solution you'd like**
Could we have a min year and max year box below that such that if the slider bar updates the graph, it updates the min year max year boxes, and if the min year max year boxes update the graph, they update the slider bar? Then users could work with whichever works best for them.

**Describe alternatives you've considered**
If my solution is too hard, we can stick with the slider bar.

**Additional context**

**Comment by miserman** [comment]
57c5f2b6dd2ad7ff6b52059fc7bf43acd8cebbbf replaces the slider with min and max inputs.
