### ISSUE TITLE
Axes do not always start at zero

### ISSUE THREAD

**Issue by ErnstMelchior** [ICJIA/arrest_explorer#14]
**Describe Issue**
Graphs are scaling to the lowest value on the graph.  That is not accepted by many researchers.  If we look at the arrests by year, it looks like they go to zero, and lots of people need the visual to see what really was happening.

**Location of Text or Control**
Arrests By Year
on the graph.  That is not accepted by many researchers.  If we look at the arrests by year, it looks like they go to zero, and lots of people need the visual to see what really was happening.

**Current Text or Control**
Lowest value on the scale of the graph at left.

**Proposed new text/control**
All graphs should scale to zero.

**Comment by miserman** [comment]
This could be the same as #15, relating to standardizing versus optimizing the y-axis range.

These strategies each have positives and negatives:

#### Standardization:
```diff
+ makes it easier to appreciate and compare absolute values
- completely hides visual elements in some cases
- can make it harder to see and compare differences (over time or between groups)
```

#### Optimization:
```diff
+ makes it easier to compare relative values
+ more consistently displays data
- may be misleading at first glance (making values look more similar, and differences more meaningful)
```

b887aeb0b88b198d64ad5392ac6f2a421a924c7e adds an option to standardize or not, and I think the default should be to not standardize.

**Comment by miserman** [comment]
bcdceced653c61c4dcd7ef57d1158c7fb46658c4 changes the default to standardize.

**Comment by kgruschow** [comment]
close as duplicate/merge with #15
