### ISSUE TITLE
Click on graph functionality is confusing, redundant, and unpredictable.

### ISSUE THREAD

**Issue by kgruschow** [ICJIA/arrest_explorer#17]
**Describe Issue**

Many text elements of graphs are in fact clickable controls. For example clicking the legend of the bottom of the graph: 
![image](https://user-images.githubusercontent.com/48029452/118311521-a2e61500-b4b5-11eb-8890-5d94e048b96c.png)

produces a menu of other options, including variables not even selected within the data tab. It is not entirely clear what will happen before selecting a new option and depending on the filters/compatibility it is possible to inadvertently wipe portions of settings in the Data tab.

Also clicking on the title of the plot toggles whether or not results are broken down by year:
![image](https://user-images.githubusercontent.com/48029452/118311893-2273e400-b4b6-11eb-93ee-0dfb56cfd5b9.png)

This is more consistent, but unexpected, and ultimately confusing.

**Current Text or Control**
title and bottom legend of plots. seems to be any plot

**Proposed new text/control**
this functionality can simply be removed. Users do not expect it here, it is hard to understand here, and exists elsewhere.

**Comment by miserman** [comment]
bcdceced653c61c4dcd7ef57d1158c7fb46658c4 removes this functionality.
