### ISSUE TITLE
Average not fully labelled

### ISSUE THREAD

**Issue by kgruschow** [ICJIA/arrest_explorer#18]
**Describe Issue**
When simply showing a single variable (e.g. arrests) averaged over years, the graph/plot is just says 'average'. In this context by general APA  standards, such it should be the average of something.

**Location of Text or Control**
Select data menu, de-select all filters and by variables, de-select year to produce a bar graph just showing the average for multiple years.

**Current Text or Control**
![image](https://user-images.githubusercontent.com/48029452/118489835-e83b5a00-b6e2-11eb-9bcc-1eba7c64ba45.png)

**Proposed new text/control**
the lower label should reflect the subject e.g. averages arrests. 

In contrast the title should reflect arrests by year

**Comment by miserman** [comment]
[`b54baa5`](https://github.com/ICJIA/arrest_explorer/commit/b54baa5e3aa84d8bfff806abf279c47da8c6a8b2#diff-27653c212e1cfe533e4eb2f7d0d3f89604c9de48a09583b4cbbbcbd08a07da79R1064) changed the x-axis label to "Overall" in this case, since that axis displays split levels (here, none).

It might make sense to label by year range (e.g., "Between 2009 and 2019"), though that is redundant with the subheading.

It's a little weird because a plot like this wouldn't normally be shown.

**Comment by kgruschow** [comment]
Reviewed this issue, conceptually it is less about the label and more about what should occur in a situation where the user just wants a single value, e.g. average arrests between years. I will have to document better as it also intersects with how years are selected and the special treatment given to years in the app and specifically the sidebar UI

**Comment by miserman** [comment]
57c5f2b6dd2ad7ff6b52059fc7bf43acd8cebbbf changes to just showing a number in this case. It also adds year information to the average table display, which I think also came up.

**Comment by kgruschow** [comment]
Hi,

this solution is the right direction

![image](https://user-images.githubusercontent.com/48029452/121376397-1ccbbb80-c907-11eb-948e-50b4b814be98.png)


few changes still needed I think: 
1. "were" instead of "where"
2.  reduce interline spacing somewhat
3. reduce font size of the number to match other text. the color and position is sufficient emphasis.

**Comment by miserman** [comment]
069620a9fd1f27df5df7dc8e7bb99cfba33ab9ea makes those changes.

**Comment by kgruschow** [comment]
I think this is good now
