### ISSUE TITLE
API ignores invalid arguments and returns potentially misleading data.

### ISSUE THREAD

**Issue by kgruschow** [ICJIA/arrest_explorer#2]
[Example](https://icjia.illinois.gov/arrestexplorer/api/?value=arrestees&format_table=tall&race=White&split=gender)

returns all arrestees, even though there is badly formed filter argument. API should *not* fail gracefully from user perspective, but at least fail if a bad argument is given. Otherwise User may receive data and not understand what they received.

**Comment by kgruschow** [comment]
Related to #7

**Comment by miserman** [comment]
bcdceced653c61c4dcd7ef57d1158c7fb46658c4 adds validation, so anything that isn't applicable should result in a 400 response.

**Comment by kgruschow** [comment]
confirmed that it is now appropriately intolerant.
