### ISSUE TITLE
vertical scrolling disappears if data menu toggled 2-3x

### ISSUE THREAD

**Issue by kgruschow** [ICJIA/arrest_explorer#22]
**Describe the bug**
The vertical scroll bar vanishes

**To Reproduce**
1. Using this plot : https://icjia.illinois.gov/arrestexplorer/?split=race,age_group
2. close/open data menu several times 
3. eventually scroll disappears

**Expected behavior**
vertical scroll bar should remain whenever additional content is available.

**Screenshots**
![image](https://user-images.githubusercontent.com/48029452/121371000-d1afa980-c902-11eb-807f-10d10d3c0b4e.png)

**Environment**
 - Device: x86 ThinkPad running Windows 10
 - Browser: Firefox

**Workarounds**
reload seems to work

**Additional context**
found while testing #16 where it is slowing testing of spacing in alternate views etc.

**Comment by kgruschow** [comment]
additional testing, this seems to occur when: the vertical scroll was visible, then user opens data menu resulting in two vertical scroll bars, then when data menu is closed both the data and data menu scroll bars vanish, potentially stranding the user.

the workaround is also more limited than expected. essentially user has to be lucky or aware of the issue and leave data menu open to ensure it does not vanish.

**Comment by miserman** [comment]
069620a9fd1f27df5df7dc8e7bb99cfba33ab9ea should fix this.
