### ISSUE TITLE
export URL can break

### ISSUE THREAD

**Issue by kgruschow** [ICJIA/arrest_explorer#5]
after loading this:
[link](https://icjia.illinois.gov/arrestexplorer/?format_table=tall&value=arrestees&split=race,county&format_category=indices&country[label]=champaign,adams)

while adjusting other settings both in the app and using working external links.. the export link function failed and is only showing main URL.

![dead export URL A](https://user-images.githubusercontent.com/48029452/117356245-22059880-ae79-11eb-8ee7-76c1da251357.PNG)
![dead export URL B](https://user-images.githubusercontent.com/48029452/117356246-22059880-ae79-11eb-8dc5-a46a92f09509.PNG)

**Comment by miserman** [comment]
57c5f2b6dd2ad7ff6b52059fc7bf43acd8cebbbf should fix this.

**Comment by kgruschow** [comment]
i've not re-experienced this exact issue, however this morning, I did have a URL that specified the filter groups twice. I will have to test further before closing.

**Comment by kgruschow** [comment]
i've not been able to replicate in informal testing, closing.
