### ISSUE TITLE
Application produced API does not respect filter arguments

### ISSUE THREAD

**Issue by kgruschow** [ICJIA/arrest_explorer#7]
**Describe the bug**
After selecting a specific plot/query via application, and copying API call to new window, the API call does not filter the results as the application did. 

**To Reproduce**
1. Go to 'https://icjia.illinois.gov/arrestexplorer/'
2. Click on 'Data '
3. In the Data menu, select Arrestees, show averages, and split by Race, then filter for 2014-2019, and race[label]=Black and/or Hispanic. View was bar graph.
4. The plot should correctly show as per screenshot. 
![Plot for Defect involving API Calls](https://user-images.githubusercontent.com/48029452/117467423-4913a700-af19-11eb-8ac6-2f372b761ba0.PNG)
5. once setup, click on Export option. Then copy and paste code for the API call to a new window. 
6. Specific API Call: [https://icjia.illinois.gov/arrestexplorer/api/?format_table=tall&value=arrestees&split=race&year%3E=2014&by_year=false&format_category=codes&race[label]=african%20american,hispanic](https://icjia.illinois.gov/arrestexplorer/api/?format_table=tall&value=arrestees&split=race&year%3E=2014&by_year=false&format_category=codes&race[label]=african%20american,hispanic)
7. result is not filtered for Race as application is and code appears to be. (see attached)

**Expected behavior**
User expects that the API code will have the exact same data shown as the application, and be filtered as per application and syntax of the API call.

**Environment**
 - Device: Windows 10
 - Browser: Firefox

**Workarounds**
If the user downloads from the export menu inside the application, it is correctly filtered.

**Additional context**
This was recording during the demo.

**Comment by miserman** [comment]
bcdceced653c61c4dcd7ef57d1158c7fb46658c4 should fix this.

**Comment by kgruschow** [comment]
![image](https://user-images.githubusercontent.com/48029452/121367333-da52b080-c8ff-11eb-968c-151fc271cbc9.png)

the generate API call: https://icjia.illinois.gov/arrestexplorer/api/?split=county&county[label]=cook%20chicago,cook%20county%20suburbs,dupage,kane,lake,madison

results in the following response: 
![image](https://user-images.githubusercontent.com/48029452/121367532-feae8d00-c8ff-11eb-9dc7-b4c07b414b8a.png)


So the behavior seems altered, however filters, at least of the county[label]=cook,champaign variety are not working.

As another example from manual/R testing: 
https://icjia.illinois.gov/arrestexplorer/api/?format_table=tall&value=arrestees&split=race,county&format_category=indices&county[label]=douglas,dupage,edgar,edwards

fails with result that edwards is invalid, at the same time, the call omitting &county[label]=... works fine.

**Comment by miserman** [comment]
069620a9fd1f27df5df7dc8e7bb99cfba33ab9ea should fix this. The issue was that entered levels were being lowercased and compared against capitalized versions. The fix was to standardize all entered levels to the capitalized form, though keeping labels as-entered would be stricter.
