### ISSUE TITLE
Font Size of Label too small

### ISSUE THREAD

**Issue by ErnstMelchior** [ICJIA/arrest_explorer#9]
**Describe Issue**
The interior font size of the label with two selections is too small.
**Location of Text or Control**
Note the "female" label in the top of the two graphs below.
![image](https://user-images.githubusercontent.com/41635929/118011230-68457680-b315-11eb-9fde-339b3e2b1ae6.png)

**Current Text or Control**
The Gender: Female and Gender: Male labels, but this is also true for any other selection that has two items.

**Proposed new text/control**
Triple the size of the font.

**Comment by kgruschow** [comment]
This seems like it might be part of #6

**Comment by miserman** [comment]
bcdceced653c61c4dcd7ef57d1158c7fb46658c4 makes these a little bigger.

**Comment by kgruschow** [comment]
The issue is improved/resolved, I would rather handle legibility of text size as part of #6 as well.
